package com.wasted.domesurvival.forge.dome;

import com.wasted.domesurvival.core.dome.DomeSpec;
import com.wasted.domesurvival.forge.data.DomeSavedData;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Vec3i;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructurePlaceSettings;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager;

import java.util.ArrayList;
import java.util.List;

/**
 * Exports and imports the complete above-ground dome as manageable structure tiles.
 * New-world terrain below Y=59 is never touched.
 */
public final class LastWorldDomeTransfer {
    private static final int TILE_SIZE = 32;
    private static final int MIN_Y = DomeSpec.wastedV1().foundationMinY();
    private static final int MAX_Y = 127;
    private static final int MIN_X = DomeSpec.wastedV1().centerX() - DomeSpec.wastedV1().surfaceRadius() - 4;
    private static final int MAX_X = DomeSpec.wastedV1().centerX() + DomeSpec.wastedV1().surfaceRadius() + 4;
    private static final int MIN_Z = DomeSpec.wastedV1().centerZ() - DomeSpec.wastedV1().surfaceRadius() - 4;
    private static final int MAX_Z = Math.max(
            DomeSpec.wastedV1().centerZ() + DomeSpec.wastedV1().surfaceRadius() + 4,
            DomeSpec.wastedV1().airlockEndZ() + 4
    );

    private LastWorldDomeTransfer() {
    }

    public static TransferResult exportDome(ServerLevel level) {
        StructureTemplateManager manager = level.getServer().getStructureManager();
        DomeSpec sourceSpec = DomeSavedData.get(level).domeSpec();
        int saved = 0;
        long blocks = 0L;

        for (Tile tile : tiles()) {
            StructureTemplate template = manager.getOrCreate(tile.id());
            BlockPos sourceOrigin = targetOrigin(tile, sourceSpec);
            template.fillFromWorld(level, sourceOrigin, tile.size(), true, Blocks.STRUCTURE_VOID);
            if (!manager.save(tile.id())) {
                return new TransferResult(false, saved, blocks, "Failed to save " + tile.id());
            }
            saved++;
            blocks += volume(tile.size());
        }
        return new TransferResult(true, saved, blocks,
                "Saved movable dome at " + sourceSpec.centerX() + ","
                        + sourceSpec.baseY() + "," + sourceSpec.centerZ()
                        + " under generated/domesurvival/structures/lastworld");
    }

    public static TransferResult importDome(ServerLevel level) {
        return importDome(level, DomeSpec.wastedV1());
    }

    public static TransferResult importDome(ServerLevel level, DomeSpec targetSpec) {
        StructureTemplateManager manager = level.getServer().getStructureManager();
        StructurePlaceSettings settings = new StructurePlaceSettings()
                .setIgnoreEntities(false)
                .setFinalizeEntities(true);
        int placed = 0;
        long blocks = 0L;

        for (Tile tile : tiles()) {
            StructureTemplate template = manager.get(tile.id()).orElse(null);
            if (template == null) {
                return new TransferResult(false, placed, blocks,
                        "Missing " + tile.id() + "; copy the exported lastworld directory first");
            }
            BlockPos targetOrigin = targetOrigin(tile, targetSpec);
            boolean success = template.placeInWorld(
                    level, targetOrigin, targetOrigin, settings,
                    RandomSource.create(level.getSeed() ^ targetOrigin.asLong()),
                    Block.UPDATE_ALL
            );
            if (!success) {
                return new TransferResult(false, placed, blocks, "Failed to place " + tile.id());
            }
            placed++;
            blocks += volume(tile.size());
        }

        level.setDefaultSpawnPos(new BlockPos(targetSpec.centerX(), targetSpec.baseY(), targetSpec.centerZ()), 0.0F);
        DomeSavedData saved = DomeSavedData.get(level);
        saved.setDomeLocation(new BlockPos(targetSpec.centerX(), targetSpec.baseY(), targetSpec.centerZ()));
        saved.markStructureVersion(DomeGenerationService.CURRENT_STRUCTURE_VERSION);
        saved.resetAirlock();
        return new TransferResult(true, placed, blocks,
                "Dome surface transferred and activated; terrain at Y<=58 remained generated by LastWorld");
    }

    public static String boundsDescription(ServerLevel level) {
        DomeSpec source = DomeSpec.wastedV1();
        DomeSpec actual = DomeSavedData.get(level).domeSpec();
        int dx = actual.centerX() - source.centerX();
        int dy = actual.baseY() - source.baseY();
        int dz = actual.centerZ() - source.centerZ();
        return (MIN_X + dx) + "," + (MIN_Y + dy) + "," + (MIN_Z + dz)
                + " .. "
                + (MAX_X + dx) + "," + (MAX_Y + dy) + "," + (MAX_Z + dz);
    }

    public static List<Tile> tiles() {
        List<Tile> result = new ArrayList<>();
        int tileX = 0;
        for (int x = MIN_X; x <= MAX_X; x += TILE_SIZE, tileX++) {
            int tileZ = 0;
            for (int z = MIN_Z; z <= MAX_Z; z += TILE_SIZE, tileZ++) {
                int sizeX = Math.min(TILE_SIZE, MAX_X - x + 1);
                int sizeZ = Math.min(TILE_SIZE, MAX_Z - z + 1);
                result.add(new Tile(
                        new ResourceLocation("domesurvival", "lastworld/dome_" + tileX + "_" + tileZ),
                        new BlockPos(x, MIN_Y, z),
                        new Vec3i(sizeX, MAX_Y - MIN_Y + 1, sizeZ)
                ));
            }
        }
        return List.copyOf(result);
    }

    public static BlockPos targetOrigin(Tile tile, DomeSpec targetSpec) {
        DomeSpec sourceSpec = DomeSpec.wastedV1();
        return tile.origin().offset(
                targetSpec.centerX() - sourceSpec.centerX(),
                targetSpec.baseY() - sourceSpec.baseY(),
                targetSpec.centerZ() - sourceSpec.centerZ()
        );
    }

    private static long volume(Vec3i size) {
        return (long) size.getX() * size.getY() * size.getZ();
    }

    public record Tile(ResourceLocation id, BlockPos origin, Vec3i size) {
    }

    public record TransferResult(boolean success, int tiles, long blockPositions, String message) {
    }
}
